-- 02_create_vector_table.sql
-- Purpose:
--   Create the SUPPORT_NOTES table with a VECTOR column.
--
-- Run as:
--   sqlplus vector_lab/VectorLab_2026@KBPDB @sql/02_create_vector_table.sql

SET ECHO ON
SET FEEDBACK ON

PROMPT ===== Connected User =====
SHOW USER;

PROMPT ===== Dropping Old SUPPORT_NOTES Table If It Exists =====

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE support_notes PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -942 THEN
            NULL;
        ELSE
            RAISE;
        END IF;
END;
/

PROMPT ===== Creating SUPPORT_NOTES Table =====

CREATE TABLE support_notes (
    note_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR2(200) NOT NULL,
    category     VARCHAR2(50),
    note_text    VARCHAR2(4000),
    embedding    VECTOR(5, FLOAT32),
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);

PROMPT ===== Table Description =====
DESC support_notes;

PROMPT ===== Script Completed =====
